// Shared constants — safe to import in both server (convex/) and client (app/) code

export const CARDS = [
  { id: 0, title: "The Bridge Keeper", icon: "\u{1F309}", color: "#006DB7", rule: "You hold the only bridge pieces in the city. Nothing can connect across the river without you. Your cooperation is not optional \u2014 it is structural.", hrNote: "Give to someone who tends to stay on the sidelines. This card makes them structurally unmissable." },
  { id: 1, title: "The Centre Node", icon: "\u26A1", color: "#F47B20", rule: "Your district must sit at the exact centre of the city grid. Every route passes through you, whether anyone planned it or not.", hrNote: "Good for someone who dominates \u2014 being fixed at the centre means others must design around them, not for them." },
  { id: 2, title: "The Last Builder", icon: "\u{1F3DB}\uFE0F", color: "#E3000B", rule: "You build last. Before finishing your district, you must physically incorporate one visible element from every other person's build into yours. You complete the city.", hrNote: "Assign to the most junior or quietest person. They literally finish the city \u2014 a structural guarantee their contribution matters most." },
  { id: 3, title: "Double Resource", icon: "\u{1F48E}", color: "#00A650", rule: "Your LEGO kit has twice the pieces of everyone else. You may only use half of them. The rest must be distributed to other players before you start building.", hrNote: "Good for senior leaders. Forces generosity and active attention to what others need \u2014 not just what they want to build." },
  { id: 4, title: "Vertical Only", icon: "\u{1F3D7}\uFE0F", color: "#FFD700", rule: "You can only build upward, never outward. Your district rises into the sky \u2014 it does not spread across the ground. Height is your entire contribution.", hrNote: "Good for someone who tends to take up a lot of space in discussions. Physically constrains their footprint." },
  { id: 5, title: "The Connector", icon: "\u{1F517}", color: "#9B59B6", rule: "Your district has no fixed position in the city. You go last in placement and fill whatever gap the city most needs. Your power is total flexibility \u2014 and total dependency on others going first.", hrNote: "Good for adaptable team members. Also useful for someone who always waits for others to decide before acting." },
  { id: 6, title: "The Gatekeeper", icon: "\u{1F6AA}", color: "#C0392B", rule: "Your district controls the only entry and exit point to the city. Before any other player places their district on the city map, they must describe their district to you and get your verbal approval. You may ask one question.", hrNote: "Give to someone quiet who has good judgment but rarely gets to exercise it formally. This card gives them structural authority." },
  { id: 7, title: "The Architect's Debt", icon: "\u{1F4D0}", color: "#16A085", rule: "Before placing any LEGO piece, you must first ask two other players for one piece each. You cannot start until both have given you something. Your district is literally built from the team.", hrNote: "Good for someone who works very independently. Forces them to initiate contact and depend on others from the very first move." },
];
